### ISSUE TITLE
Show Jackpot if Won

### ISSUE THREAD

**Issue by RHavar** [moneypot/dustdice#12]
When winning the jackpot, it should have some special thing to show you won the jackpot. Maybe a nice icon or image or something. This will require vault to fully support it (vault issue 30)

**Comment by rakeshok** [comment]
I'll try faking it for now, to create the UI for that

**Comment by RHavar** [comment]
One easy way to fake it, is check  `if (profit == jackpot)` ... that will work, except in the case the person is trying to win exactly the jackpot. For now, it's ok if we show that as a false positive. If you wanted to be technical, you could check if the outcome means you should have lost but you won anyway (in which case you won the jackpot)
