### ISSUE TITLE
hash ip's on vault.moneypot.com/me/security

### ISSUE THREAD

**Issue by pokeball99** [moneypot/dustdice#32]

**Comment by RHavar** [comment]
Why? :o I don't think exposing a persons own ip address is bad, sites like google do it as well

**Comment by pokeball99** [comment]
just because some people like to hide there info as much as possible,that one reason that bitcoin is so popular

**Comment by RHavar** [comment]
Only you can see your own ip address, no one else can =)

**Comment by pokeball99** [comment]
but still..

**Comment by RHavar** [comment]
They're only there for 2 weeks, it's a very useful tool for people to ensure they are the only ones accessing their own accounts =)
