### ISSUE TITLE
Reporting vault "Server side error"

### ISSUE THREAD

**Issue by RHavar** [moneypot/dustdice#4]
Just trying DustDice, got a "Server side error" page -- although I don't think there was one. Only if the server returns 5xx was it a server-side error. In this case, it appears to be a 403 -- which means it's information the client should handle.

If it's something unhandled, you should report it to the user so they can at least see it :D

**Comment by RHavar** [comment]
Also, in this specific case the error is "BANKROLL_NOT_BIG_ENOUGH" which means they're betting more than our bankroll can handle. This is something we need to gracefully handle, and tell the user to try win less

**Comment by rakeshok** [comment]
Yeah, just realize this error existed, also what codes will this kind of errors will use?

**Comment by rakeshok** [comment]
Should be fixed on https://github.com/moneypot/dustdice/commit/c85c8f0196da08f21c9e7badfc8a5c8fd83fbe14
