### ISSUE TITLE
Configurable Jackpot

### ISSUE THREAD

**Issue by RHavar** [moneypot/dustdice#5]
Especially for testing dustdice.com, our bankroll isn't big enough to support a 1 BTC jackpot. So let's use a jackpot of 10k bits, and possibly expose it in the settings ui.

This will also allow us to do a good job at making sure the jackpot works! :D

**Comment by RHavar** [comment]
I've lowered the jackpot setting, but we should probably allow people to configure it themselves in the settings

**Comment by rakeshok** [comment]
So the vault API will have a default jackpot like now and the possibility of setting your own, or how exactly the new API will work, also if there is a default jackpot will vault return it when getting user data?
