### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by RHavar** [moneypot/dustdice#80]
oh

`.modal { overflow: scroll }`

`it should be overflow-y: scroll`

you almost never want `overflow: scroll`. it forces the scrollbars to be there even if there's nothing to scroll. only useful in, say, a white-on-white chatbox so ppl know it will eventually scroll.

`overflow: auto`

i would change it to `overflow-y: auto`. there's no reason for modal to scroll horizontally, just vertically

**Comment by rakeshok** [comment]
https://github.com/moneypot/dustdice/commit/6874db9ba14d13514dc451a9a798ea4f5a1e0fc1
